import type { WeddingContent } from '@/types/wedding';

export const FALLBACK_MEDIA = {
  hero: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=1800&q=85',
  groom:
    'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=900&q=85',
  bride:
    'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=900&q=85',
  gallery: [
    'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1522673607200-164d1b6ce486?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1537633552985-df8429e8048b?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1606800052052-a08af7148866?auto=format&fit=crop&w=1200&q=82',
  ],
  story: [
    'https://images.unsplash.com/photo-1523438885200-e635ba2c371e?auto=format&fit=crop&w=1200&q=84',
    'https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?auto=format&fit=crop&w=1200&q=84',
    'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=1200&q=84',
    'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=84',
  ],
  video: '/video/wedding-demo.mp4',
  videoPoster: '/images/video-poster.svg',
  music: '/audio/wedding-demo.mp3',
};

const futureDate = '2027-07-17T09:00:00+07:00';

export const FALLBACK_CONTENT: WeddingContent = {
  id: '11111111-1111-4111-8111-111111111111',
  slug: 'nathan-dan-aulia',
  title: 'Pernikahan Nathan & Aulia',
  status: 'published',
  groomName: 'Nathan Pratama',
  brideName: 'Aulia Rahma',
  eventDate: futureDate,
  timezone: 'Asia/Jakarta',
  quote:
    'Di antara banyak langkah dalam hidup, kami memilih berjalan pulang menuju satu sama lain.',
  thankYouMessage:
    'Kehadiran dan doa restu Anda menjadi hadiah paling bermakna dalam perjalanan baru kami.',
  pastEventMessage:
    'Hari bahagia kami telah berlangsung. Terima kasih telah menjadi bagian dari cerita ini.',
  heroImageUrl: FALLBACK_MEDIA.hero,
  couples: [
    {
      id: 'groom-demo',
      role: 'groom',
      fullName: 'Nathan Pratama, S.T.',
      nickname: 'Nathan',
      parentNames: 'Putra pertama Bapak Arif Pratama & Ibu Dina Maharani',
      photoUrl: FALLBACK_MEDIA.groom,
      instagramUrl: 'https://instagram.com/',
      description:
        'Sosok tenang yang percaya bahwa rumah terbaik adalah tempat dua orang saling bertumbuh.',
      sortOrder: 1,
    },
    {
      id: 'bride-demo',
      role: 'bride',
      fullName: 'Aulia Rahma, S.Psi.',
      nickname: 'Aulia',
      parentNames: 'Putri kedua Bapak Hendra Saputra & Ibu Ratna Wulandari',
      photoUrl: FALLBACK_MEDIA.bride,
      instagramUrl: 'https://instagram.com/',
      description:
        'Pribadi hangat yang menemukan bahagia dalam keluarga, doa, dan cerita sederhana.',
      sortOrder: 2,
    },
  ],
  events: [
    {
      id: 'event-akad',
      eventType: 'akad',
      title: 'Akad Nikah',
      date: '2027-07-17',
      startTime: '09:00',
      endTime: '10:30',
      timezone: 'Asia/Jakarta',
      venueName: 'Pendopo Arunika',
      address: 'Jl. Taman Bahagia No. 17, Jakarta Selatan, DKI Jakarta',
      latitude: -6.2615,
      longitude: 106.8106,
      googleMapsUrl: 'https://maps.google.com/?q=-6.2615,106.8106',
      dressCode: 'Formal bernuansa earth tone',
      notes: 'Mohon hadir 30 menit sebelum acara dimulai.',
      sortOrder: 1,
    },
    {
      id: 'event-resepsi',
      eventType: 'resepsi',
      title: 'Resepsi Pernikahan',
      date: '2027-07-17',
      startTime: '11:00',
      endTime: '14:00',
      timezone: 'Asia/Jakarta',
      venueName: 'Pendopo Arunika',
      address: 'Jl. Taman Bahagia No. 17, Jakarta Selatan, DKI Jakarta',
      latitude: -6.2615,
      longitude: 106.8106,
      googleMapsUrl: 'https://maps.google.com/?q=-6.2615,106.8106',
      dressCode: 'Batik atau busana formal',
      notes: 'Area parkir tersedia di sisi timur gedung.',
      sortOrder: 2,
    },
  ],
  loveStories: [
    {
      id: 'story-1',
      title: 'Pertama Bertemu',
      date: '2021-08-21',
      imageUrl: FALLBACK_MEDIA.story[0],
      story:
        'Sebuah pertemuan singkat di acara sahabat berubah menjadi percakapan yang tidak ingin segera diakhiri.',
      sortOrder: 1,
    },
    {
      id: 'story-2',
      title: 'Mulai Berkomitmen',
      date: '2022-02-12',
      imageUrl: FALLBACK_MEDIA.story[1],
      story:
        'Kami belajar bahwa hubungan bukan tentang selalu sepakat, melainkan tetap memilih saling memahami.',
      sortOrder: 2,
    },
    {
      id: 'story-3',
      title: 'Lamaran',
      date: '2026-11-15',
      imageUrl: FALLBACK_MEDIA.story[2],
      story:
        'Di hadapan keluarga, kami mengikat niat baik dan memohon restu untuk melangkah ke jenjang berikutnya.',
      sortOrder: 3,
    },
    {
      id: 'story-4',
      title: 'Hari Pernikahan',
      date: '2027-07-17',
      imageUrl: FALLBACK_MEDIA.story[3],
      story:
        'Dengan penuh syukur, kami akan memulai babak baru sebagai keluarga.',
      sortOrder: 4,
    },
  ],
  media: FALLBACK_MEDIA.gallery.map((url, index) => ({
    id: `gallery-${index + 1}`,
    type: 'image',
    url,
    caption: [
      'Satu cerita',
      'Tawa yang sama',
      'Langkah bersama',
      'Dalam doa',
      'Menuju rumah',
      'Selamanya',
    ][index],
    altText: `Foto prewedding Nathan dan Aulia ${index + 1}`,
    featured: index === 0,
    sortOrder: index + 1,
  })),
  gifts: [
    {
      id: 'gift-1',
      giftType: 'bank',
      bankName: 'Bank Central Asia',
      accountNumber: '1234567890',
      accountHolder: 'Nathan Pratama',
      sortOrder: 1,
    },
    {
      id: 'gift-2',
      giftType: 'bank',
      bankName: 'Bank Syariah Indonesia',
      accountNumber: '7890123456',
      accountHolder: 'Aulia Rahma',
      sortOrder: 2,
    },
  ],
  guests: [
    {
      id: 'guest-1',
      name: 'Bapak Andi dan Keluarga',
      greeting: 'Bapak/Ibu',
      phone: '6281234567801',
      group: 'Keluarga',
      invitationQuota: 4,
      slug: 'bapak-andi-keluarga',
      token: 'tok-demo-1',
      invitationStatus: 'sudah_dikirim',
      rsvpStatus: 'hadir',
    },
    {
      id: 'guest-2',
      name: 'Siti Maharani',
      greeting: 'Saudari',
      phone: '6281234567802',
      group: 'Sahabat',
      invitationQuota: 2,
      slug: 'siti-maharani',
      token: 'tok-demo-2',
      invitationStatus: 'sudah_dikirim',
      rsvpStatus: 'ragu',
    },
    {
      id: 'guest-3',
      name: 'Rizky Hidayat',
      greeting: 'Saudara',
      phone: '6281234567803',
      group: 'Kantor',
      invitationQuota: 1,
      slug: 'rizky-hidayat',
      token: 'tok-demo-3',
      invitationStatus: 'belum_dikirim',
      rsvpStatus: 'belum',
    },
    {
      id: 'guest-4',
      name: 'Keluarga Besar Wijaya',
      greeting: 'Bapak/Ibu',
      phone: '6281234567804',
      group: 'Keluarga',
      invitationQuota: 5,
      slug: 'keluarga-besar-wijaya',
      token: 'tok-demo-4',
      invitationStatus: 'sudah_dikirim',
      rsvpStatus: 'tidak_hadir',
    },
    {
      id: 'guest-5',
      name: 'Dewi Lestari',
      greeting: 'Saudari',
      phone: '6281234567805',
      group: 'Sahabat',
      invitationQuota: 2,
      slug: 'dewi-lestari',
      token: 'tok-demo-5',
      invitationStatus: 'belum_dikirim',
      rsvpStatus: 'belum',
    },
  ],
  messages: [
    {
      id: 'msg-1',
      guestName: 'Siti Maharani',
      message:
        'Semoga menjadi keluarga yang penuh sakinah, mawaddah, dan rahmah.',
      attendanceStatus: 'hadir',
      approved: true,
      createdAt: '2026-07-12T08:00:00+07:00',
    },
    {
      id: 'msg-2',
      guestName: 'Keluarga Wijaya',
      message:
        'Selamat menempuh hidup baru. Semoga selalu saling menjaga dalam suka dan duka.',
      attendanceStatus: 'tidak_hadir',
      approved: true,
      createdAt: '2026-07-13T09:15:00+07:00',
    },
    {
      id: 'msg-3',
      guestName: 'Rizky Hidayat',
      message:
        'Turut berbahagia untuk Nathan dan Aulia. Sampai bertemu di hari bahagia!',
      attendanceStatus: 'ragu',
      approved: true,
      createdAt: '2026-07-14T12:20:00+07:00',
    },
  ],
  musicUrl: FALLBACK_MEDIA.music,
  musicTitle: 'Wedding Chime — Demo Audio',
  videoUrl: FALLBACK_MEDIA.video,
  videoPosterUrl: FALLBACK_MEDIA.videoPoster,
  theme: {
    preset: 'luxury-gold',
    layoutPreset: 'cinematic-editorial',
    coverStyle: 'curtain',
    navigationStyle: 'floating-dock',
    galleryStyle: 'masonry',
    storyStyle: 'cinematic',
    primary: '#1d1f19',
    secondary: '#f5f0e6',
    accent: '#c2a25b',
    text: '#292922',
    surface: '#fffaf0',
    muted: '#746c5d',
    headingFont: 'Cormorant Garamond',
    bodyFont: 'Manrope',
    mode: 'light',
    animationIntensity: 'medium',
    layoutStyle: 'editorial',
    ornamentStyle: 'gold-lines',
    heroStyle: 'cinematic',
    surfaceStyle: 'glass',
    cornerStyle: 'soft',
  },
  whatsappTemplate:
    'Assalamu’alaikum Bapak/Ibu/Saudara/i [Nama Tamu]. Tanpa mengurangi rasa hormat, kami mengundang Anda untuk menghadiri acara pernikahan kami. Silakan membuka undangan melalui tautan berikut: [Link Undangan]',
  seo: {
    title: 'Undangan Pernikahan Nathan & Aulia',
    description:
      'Dengan penuh kebahagiaan, Nathan dan Aulia mengundang Anda untuk hadir pada hari pernikahan kami.',
    imageUrl: FALLBACK_MEDIA.hero,
  },
};
